services:
  pokedex-api:
    build:
      context: .
      dockerfile: src/Pokedex.Api/Dockerfile
    container_name: pokedex-api
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped
